const express = require('express')
const router = express.Router()
const LoaispconController = require('../controllers/loaispconController')
router.post('/loaispcon/create/:ParentID',LoaispconController.createLoaiSPCon)
router.get('/loaispcon/getallspconByParentID/:ParentID',LoaispconController.getSPConByParentID)
router.get('/loaispcon/getLoaiSPConByID/loaisanphamconID',LoaispconController.addSanPham)
router.put('/loaispcon/:loaispconID/removeSanPham/:sanphamID',LoaispconController.removeSanPham)
router.put('/loaispcon/:loaispconID/addSanPham/:sanphamID',LoaispconController.addSanPham)
router.get('/loaispcon/getSoLuongByParentID/:ParentID',LoaispconController.getSoLuongByParentID)
router.put('/loaispcon/activeToggle',LoaispconController.activeToggle)
router.put('/loaispcon/editlspcon',LoaispconController.editLoaiSPConByID)
router.delete('/loaispcon/deleteLSPCon/:id',LoaispconController.deleteLSPConByID)
module.exports =router;